export const LOGIN_USER = 'USER_LOGIN';
export const REGISTER_USER = 'USER_REGISTER';
export const AUTH_USER = 'USER_AUTH';
export const LOGOUT_USER = 'USER_LOGOUT';

export const GET_PRODUCTS_BY_SELL = 'GET_PRODUCTS_BY_SELL';
export const GET_PRODUCTS_BY_ARRIVAL = 'GET_PRODUCTS_BY_ARRIVAL';
export const GET_BRANDS = 'GET_BRANDS';
export const GET_WOODS = 'GET_WOODS';
export const GET_PRODUCTS_TO_SHOP = 'GET_PRODUCTS_TO_SHOP';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT';